import gradebookData from "@/data/gradebook.json";
import attendanceData from "@/data/attendance.json";
import teacherNotesData from "@/data/teacher_notes.json";
import rosterData from "@/data/roster.json";
import { Mic, RefreshCw } from "lucide-react";
import { AttendanceSection } from "./components/AttendanceSection";
import { GradebookSection } from "./components/GradebookSection";
import { TeacherNotesSection } from "./components/TeacherNotesSection";

export default function HowItWorksPage() {
  const nameById = Object.fromEntries(
    rosterData.students.map((s) => [s.student_id, s.name]),
  );

  return (
    <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-10 px-6 py-12 font-sans">
      <header className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold tracking-tight text-foreground">
          How it works
        </h1>
        <p className="max-w-2xl text-muted-foreground">
          BridgeAI turns class records and teacher observations into suggested
          parent outreach. These are the inputs for {rosterData.class.name},
          Period {rosterData.class.period}.
        </p>
      </header>

      <section className="flex flex-col gap-8" aria-labelledby="input-data-heading">
        <div className="flex flex-col gap-1">
          <h2
            id="input-data-heading"
            className="text-xl font-semibold tracking-tight text-foreground"
          >
            Where does the input data come from?
          </h2>
          <p className="flex items-start gap-2 text-sm ml-4">
            <RefreshCw
              aria-hidden="true"
              className="mt-0.5 size-3.5 shrink-0"
              strokeWidth={2}
            />
            <span>
              Gradebook scores and attendance are pulled from the
              school&apos;s SIS. <i>(for demo purposes, we're using mock data.)</i>
            </span>
          </p>
          <p className="flex items-start gap-2 text-sm ml-4">
            <Mic
              aria-hidden="true"
              className="mt-0.5 size-3.5 shrink-0"
              strokeWidth={2}
            />
            <span>
              Structured notes are automatically generated by the teacher&apos;s
              &quot;brain dump&quot; voice recordings.
            </span>
          </p>
        </div>

        <GradebookSection
          assignments={gradebookData.assignments}
          grades={gradebookData.grades}
          nameById={nameById}
        />

        <AttendanceSection
          reportingPeriod={attendanceData.reporting_period}
          records={attendanceData.records}
          nameById={nameById}
        />

        <TeacherNotesSection
          teacher={teacherNotesData.teacher}
          notes={teacherNotesData.notes}
          nameById={nameById}
        />
      </section>
    </main>
  );
}
